server:
  port: 8083
spring:
  application:
    name: cat-demo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: *