server:
  port: 8082
spring:
  application:
    name: cat-demo-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.85:8848
management:
  endpoints:
    web:
      exposure:
        include: /*